title: GT ML7641 Project
description: This webpage presents the development of a NN capable to do image classifcation for medical applications, specifically the identification of colonorectal Cancer
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
